image:
  repository: selcpacr.azurecr.io/selfcaremspartyregistryproxy
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_PARTY_REGISTRY_PROXY_LOG_LEVEL: "DEBUG"
  MOCK_OPEN_DATA_ENABLED: "true"
  MOCK_OPEN_DATA_URL: "https://selcdcheckoutsa.z6.web.core.windows.net/resources"
  MOCK_OPEN_DATA_INSTITUTION_ENDPOINT: "/institutions-open-data-mock.csv"
  MOCK_OPEN_DATA_CATEGORY_ENDPOINT: "/categories-open-data-mock.csv"
  MOCK_OPEN_DATA_AOO_ENDPOINT: "/aoo-open-data-mock.csv"
  MOCK_OPEN_DATA_UO_ENDPOINT: "/uo-open-data-mock.csv"
  BLOB_STORAGE_CONN_STRING: "DefaultEndpointsProtocol=https;BlobEndpoint=https://selcdcheckoutsa.blob.core.windows.net/;AccountName=selcdcheckoutsa;AccountKey=5D2Eblp3/tBekLYfW2mkKUqMA48SXYHsRGzptVUnvok+NIS9TzgymBqs5EIjZ2zpm1c7s4ZS9M9+01tDeV8gKg=="
  BLOB_CONTAINER_REF: "$web"
  BLOB_PDND_FILENAME: "data.csv"
