image:
  repository: selcpacr.azurecr.io/selfcaremspartyregistryproxy
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_PARTY_REGISTRY_PROXY_LOG_LEVEL: "INFO"
  PARTY_MOCK_REGISTRY_INSTITUTIONS_URL: "https://selcdcheckoutsa.z6.web.core.windows.net/resources/ORIGIN-mock.json"
  PARTY_MOCK_REGISTRY_CATEGORIES_URL: "https://indicepa.gov.it/ipa-dati/datastore/dump/84ebb2e7-0e61-427b-a1dd-ab8bb2a84f07?format=json"
